"""albums table

Revision ID: 50386efe4896
Revises: 331d11e06424
Create Date: 2018-01-14 10:32:30.152335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50386efe4896'
down_revision = '331d11e06424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('artist', sa.String(length=140), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_last_played'), 'album', ['last_played'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_last_played'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
